### PR TITLE
add file type/extension njk as nunjucks file extension per community

### PR DESCRIPTION
**Pull request by dkebler**
tried it out in my local package install, works fine.

### CODE REVIEW

**Comment by joelbschwartz** [comment]
FWIW: https://github.com/mozilla/nunjucks/issues/685#issuecomment-186298507

**Comment by dkebler** [comment]
See this pr https://github.com/mozilla/nunjucks/pull/687
per
https://groups.google.com/forum/#!topic/nunjucks/mJbJ96OPUGQ

**Comment by ughitsaaron** [comment]
Status of this merge?

**Comment by ughitsaaron** [comment]
What's the status of this pull request?

**Comment by puranjayjain** [comment]
@ughitsaaron I have created a new language support for nunjucks and would suggest you and any other person using this repo to move [there](https://atom.io/packages/atom-language-nunjucks)

**Comment by ughitsaaron** [comment]
Thanks for the tip @puranjayjain

**Comment by joelbschwartz** [comment]
@ughitsaaron I'd strongly suggest sticking to this repository so the Atom community can keep just one download link for Nunjucks syntax highlighting. @alohaas does maintain this repository. While waiting for the file extension, you can just edit one line in the `~/.atom/packages/language-nunjucks/grammars/html (nunjucks templates).cson` file (path for OS X). On line 4, add `njk` beneath the others.

**Comment by alohaas** [comment]
Hey @dkebler thanks for the PR request. This slipped under my radar because I was not mentioned in the original comment on the PR and my notifications settings aren't set correctly. 
I appreciate your vigilance @joelbschwartz. You're right that the activity of @puranjayjain violates the MIT license. I would like to continue maintaining this repo. I will update the contribution guidelines to ensure that contributors include a mention of my username in the comment and also update my notification settings.

**Comment by alohaas** [comment]
@dkebler LGTM :+1: 
Thank you for the update.

**Comment by puranjayjain** [comment]
@ughitsaaron please ignore my tip and follow @joelbschwartz 's advice he is right and I was too hasty to declare the repo abandoned the repo is maintained.

**Pull request merged**
