### PR TITLE
added more snippets

### PR DESCRIPTION
**Pull request by puranjayjain**
added the following snippets:
- call
- else
- elif
- super
- alternate declaration for variables

### CODE REVIEW

**Comment by alohaas** [comment]
@puranjayjain reviewing this now...

**Comment by alohaas** [comment]
@puranjayjain since this is a Pull Request from an "unknown repository", I am not sure I can `checkout` this PR to test your work. What I will do is copy this to a branch, checkout that branch and test it locally. If all is good I will merge this original PR so you can still get the credit for the lines of code. 

If there were other enhancements you added to your own repo that you previously copied, I would encourage you to fork this repo and make another PR :grin:

**Comment by puranjayjain** [comment]
Ok @alohaas I'll do that I had screwed up fork earlier. Anyway I had added a few more snippets and a some additions to the docs and push the changes anyway. Ahhh don't tease me :grin: I understood your reference btw. Push changes anyhow. Will be forking and making another PR soon with a bunch of more changes. I also added this repo and the autocomplete repo to autocomplete provider wiki.

**Comment by alohaas** [comment]
Didn't realize there was an autocomplete provider wiki, that's great!
These changes look good to me. I really like the `Alt Variable` snippet you added. I think the `block` snippet could be similarly improved. 

But this LGTM :+1: 

Mergin'

**Pull request merged**
